drop table if exists airplane;
drop table if exists assessed_value;
drop table if exists car;
drop table if exists model;

create table airplane
(
    fuel_capacity integer,
    manufacturer  varchar(255),
    seats         integer,
    id            bigint not null,
    primary key (id)
);

create table assessed_value
(
    id         bigint generated by default as identity,
    date_value date,
    value      decimal(19, 2),
    object_id  bigint not null,
    primary key (id)
);

create table car
(
    power double,
    id    bigint not null,
    primary key (id)
);

create table model
(
    id            bigint generated by default as identity,
    brand         varchar(255),
    model         varchar(255),
    year_of_issue smallint,
    primary key (id)
);

alter table airplane
    add constraint fk_airplane_id_model_id foreign key (id) references model;
alter table car
    add constraint fk_car_id_model_id foreign key (id) references model;
alter table assessed_value
    add constraint fk_assessed_value_object_id_model_id foreign key (object_id) references model;
